"""Create all tables

Revision ID: 2276ac54ebc7
Revises: 
Create Date: 2020-08-19 11:34:21.538864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2276ac54ebc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversion_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('engine', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_versions_id'), 'conversion_versions', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('file_hash', sa.String(length=255), nullable=True),
    sa.Column('file_extension', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=255), nullable=True),
    sa.Column('index_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('extraction_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('engine', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_versions_id'), 'extraction_versions', ['id'], unique=False)
    op.create_table('validation_schemas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('validation_schema_json', sa.JSON(), nullable=True),
    sa.Column('file_type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_schemas_id'), 'validation_schemas', ['id'], unique=False)
    op.create_table('conversions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('conversion_version_id', sa.Integer(), nullable=True),
    sa.Column('converted_text', sa.TEXT(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversion_version_id'], ['conversion_versions.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversions_id'), 'conversions', ['id'], unique=False)
    op.create_table('doccano_monocle_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('monocle_document_id', sa.Integer(), nullable=False),
    sa.Column('doccano_document_id', sa.Integer(), nullable=False),
    sa.Column('doccano_project_id', sa.Integer(), nullable=False),
    sa.Column('extraction_version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_version_id'], ['extraction_versions.id'], ),
    sa.ForeignKeyConstraint(['monocle_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id', 'monocle_document_id', 'doccano_document_id', 'doccano_project_id')
    )
    op.create_index(op.f('ix_doccano_monocle_documents_id'), 'doccano_monocle_documents', ['id'], unique=False)
    op.create_table('document_storages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('storage_engine', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id', 'document_id', 'storage_engine', 'file_path')
    )
    op.create_index(op.f('ix_document_storages_id'), 'document_storages', ['id'], unique=False)
    op.create_table('optional_document_attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id', 'document_id', 'name', 'value')
    )
    op.create_index(op.f('ix_optional_document_attributes_id'), 'optional_document_attributes', ['id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('conversion_id', sa.Integer(), nullable=True),
    sa.Column('extraction_version_id', sa.Integer(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('new_structured_data', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversion_id'], ['conversions.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['extraction_version_id'], ['extraction_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_id'), 'extractions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extractions_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_optional_document_attributes_id'), table_name='optional_document_attributes')
    op.drop_table('optional_document_attributes')
    op.drop_index(op.f('ix_document_storages_id'), table_name='document_storages')
    op.drop_table('document_storages')
    op.drop_index(op.f('ix_doccano_monocle_documents_id'), table_name='doccano_monocle_documents')
    op.drop_table('doccano_monocle_documents')
    op.drop_index(op.f('ix_conversions_id'), table_name='conversions')
    op.drop_table('conversions')
    op.drop_index(op.f('ix_validation_schemas_id'), table_name='validation_schemas')
    op.drop_table('validation_schemas')
    op.drop_index(op.f('ix_extraction_versions_id'), table_name='extraction_versions')
    op.drop_table('extraction_versions')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversion_versions_id'), table_name='conversion_versions')
    op.drop_table('conversion_versions')
    # ### end Alembic commands ###
